name: Create New Release

on:
  workflow_dispatch:
    inputs:
      newRelease:
        required: true
        description: "Create New Release"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Release Job
        env:
          CIRCLE_BRANCH: ${{ github.head_ref }}
        run: |
          curl --location --request POST 'https://circleci.com/api/v2/project/gh/hokushin118/rps/pipeline' \
          --header 'Circle-Token: ${{ secrets.CIRCLE_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --header 'Accept: application/json' \
          --data-raw '{"branch":"${CIRCLE_BRANCH}","parameters":{"is_release":true}}'
